package com.cn.model;

import java.io.Serializable;
import java.util.Date;

public class SmComment implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_comment.SC_ID
     *
     * @mbg.generated
     */
    private Integer scId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_comment.SC_CONTENT
     *
     * @mbg.generated
     */
    private String scContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_comment.SC_CREATE_TIME
     *
     * @mbg.generated
     */
    private Date scCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_comment.SC_NICK_NAME
     *
     * @mbg.generated
     */
    private String scNickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_comment.SC_SP_ID
     *
     * @mbg.generated
     */
    private Integer scSpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sm_comment
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_comment.SC_ID
     *
     * @return the value of sm_comment.SC_ID
     *
     * @mbg.generated
     */
    public Integer getScId() {
        return scId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_comment.SC_ID
     *
     * @param scId the value for sm_comment.SC_ID
     *
     * @mbg.generated
     */
    public void setScId(Integer scId) {
        this.scId = scId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_comment.SC_CONTENT
     *
     * @return the value of sm_comment.SC_CONTENT
     *
     * @mbg.generated
     */
    public String getScContent() {
        return scContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_comment.SC_CONTENT
     *
     * @param scContent the value for sm_comment.SC_CONTENT
     *
     * @mbg.generated
     */
    public void setScContent(String scContent) {
        this.scContent = scContent == null ? null : scContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_comment.SC_CREATE_TIME
     *
     * @return the value of sm_comment.SC_CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getScCreateTime() {
        return scCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_comment.SC_CREATE_TIME
     *
     * @param scCreateTime the value for sm_comment.SC_CREATE_TIME
     *
     * @mbg.generated
     */
    public void setScCreateTime(Date scCreateTime) {
        this.scCreateTime = scCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_comment.SC_NICK_NAME
     *
     * @return the value of sm_comment.SC_NICK_NAME
     *
     * @mbg.generated
     */
    public String getScNickName() {
        return scNickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_comment.SC_NICK_NAME
     *
     * @param scNickName the value for sm_comment.SC_NICK_NAME
     *
     * @mbg.generated
     */
    public void setScNickName(String scNickName) {
        this.scNickName = scNickName == null ? null : scNickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_comment.SC_SP_ID
     *
     * @return the value of sm_comment.SC_SP_ID
     *
     * @mbg.generated
     */
    public Integer getScSpId() {
        return scSpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_comment.SC_SP_ID
     *
     * @param scSpId the value for sm_comment.SC_SP_ID
     *
     * @mbg.generated
     */
    public void setScSpId(Integer scSpId) {
        this.scSpId = scSpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_comment
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", scId=").append(scId);
        sb.append(", scContent=").append(scContent);
        sb.append(", scCreateTime=").append(scCreateTime);
        sb.append(", scNickName=").append(scNickName);
        sb.append(", scSpId=").append(scSpId);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_comment
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SmComment other = (SmComment) that;
        return (this.getScId() == null ? other.getScId() == null : this.getScId().equals(other.getScId()))
            && (this.getScContent() == null ? other.getScContent() == null : this.getScContent().equals(other.getScContent()))
            && (this.getScCreateTime() == null ? other.getScCreateTime() == null : this.getScCreateTime().equals(other.getScCreateTime()))
            && (this.getScNickName() == null ? other.getScNickName() == null : this.getScNickName().equals(other.getScNickName()))
            && (this.getScSpId() == null ? other.getScSpId() == null : this.getScSpId().equals(other.getScSpId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_comment
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getScId() == null) ? 0 : getScId().hashCode());
        result = prime * result + ((getScContent() == null) ? 0 : getScContent().hashCode());
        result = prime * result + ((getScCreateTime() == null) ? 0 : getScCreateTime().hashCode());
        result = prime * result + ((getScNickName() == null) ? 0 : getScNickName().hashCode());
        result = prime * result + ((getScSpId() == null) ? 0 : getScSpId().hashCode());
        return result;
    }
}