package com.cn.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SmCommentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sm_comment
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sm_comment
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sm_comment
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_comment
     *
     * @mbg.generated
     */
    public SmCommentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_comment
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_comment
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_comment
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_comment
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_comment
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_comment
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_comment
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_comment
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_comment
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_comment
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sm_comment
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andScIdIsNull() {
            addCriterion("SC_ID is null");
            return (Criteria) this;
        }

        public Criteria andScIdIsNotNull() {
            addCriterion("SC_ID is not null");
            return (Criteria) this;
        }

        public Criteria andScIdEqualTo(Integer value) {
            addCriterion("SC_ID =", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdNotEqualTo(Integer value) {
            addCriterion("SC_ID <>", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdGreaterThan(Integer value) {
            addCriterion("SC_ID >", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("SC_ID >=", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdLessThan(Integer value) {
            addCriterion("SC_ID <", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdLessThanOrEqualTo(Integer value) {
            addCriterion("SC_ID <=", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdIn(List<Integer> values) {
            addCriterion("SC_ID in", values, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdNotIn(List<Integer> values) {
            addCriterion("SC_ID not in", values, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdBetween(Integer value1, Integer value2) {
            addCriterion("SC_ID between", value1, value2, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdNotBetween(Integer value1, Integer value2) {
            addCriterion("SC_ID not between", value1, value2, "scId");
            return (Criteria) this;
        }

        public Criteria andScContentIsNull() {
            addCriterion("SC_CONTENT is null");
            return (Criteria) this;
        }

        public Criteria andScContentIsNotNull() {
            addCriterion("SC_CONTENT is not null");
            return (Criteria) this;
        }

        public Criteria andScContentEqualTo(String value) {
            addCriterion("SC_CONTENT =", value, "scContent");
            return (Criteria) this;
        }

        public Criteria andScContentNotEqualTo(String value) {
            addCriterion("SC_CONTENT <>", value, "scContent");
            return (Criteria) this;
        }

        public Criteria andScContentGreaterThan(String value) {
            addCriterion("SC_CONTENT >", value, "scContent");
            return (Criteria) this;
        }

        public Criteria andScContentGreaterThanOrEqualTo(String value) {
            addCriterion("SC_CONTENT >=", value, "scContent");
            return (Criteria) this;
        }

        public Criteria andScContentLessThan(String value) {
            addCriterion("SC_CONTENT <", value, "scContent");
            return (Criteria) this;
        }

        public Criteria andScContentLessThanOrEqualTo(String value) {
            addCriterion("SC_CONTENT <=", value, "scContent");
            return (Criteria) this;
        }

        public Criteria andScContentLike(String value) {
            addCriterion("SC_CONTENT like", value, "scContent");
            return (Criteria) this;
        }

        public Criteria andScContentNotLike(String value) {
            addCriterion("SC_CONTENT not like", value, "scContent");
            return (Criteria) this;
        }

        public Criteria andScContentIn(List<String> values) {
            addCriterion("SC_CONTENT in", values, "scContent");
            return (Criteria) this;
        }

        public Criteria andScContentNotIn(List<String> values) {
            addCriterion("SC_CONTENT not in", values, "scContent");
            return (Criteria) this;
        }

        public Criteria andScContentBetween(String value1, String value2) {
            addCriterion("SC_CONTENT between", value1, value2, "scContent");
            return (Criteria) this;
        }

        public Criteria andScContentNotBetween(String value1, String value2) {
            addCriterion("SC_CONTENT not between", value1, value2, "scContent");
            return (Criteria) this;
        }

        public Criteria andScCreateTimeIsNull() {
            addCriterion("SC_CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andScCreateTimeIsNotNull() {
            addCriterion("SC_CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andScCreateTimeEqualTo(Date value) {
            addCriterion("SC_CREATE_TIME =", value, "scCreateTime");
            return (Criteria) this;
        }

        public Criteria andScCreateTimeNotEqualTo(Date value) {
            addCriterion("SC_CREATE_TIME <>", value, "scCreateTime");
            return (Criteria) this;
        }

        public Criteria andScCreateTimeGreaterThan(Date value) {
            addCriterion("SC_CREATE_TIME >", value, "scCreateTime");
            return (Criteria) this;
        }

        public Criteria andScCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("SC_CREATE_TIME >=", value, "scCreateTime");
            return (Criteria) this;
        }

        public Criteria andScCreateTimeLessThan(Date value) {
            addCriterion("SC_CREATE_TIME <", value, "scCreateTime");
            return (Criteria) this;
        }

        public Criteria andScCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("SC_CREATE_TIME <=", value, "scCreateTime");
            return (Criteria) this;
        }

        public Criteria andScCreateTimeIn(List<Date> values) {
            addCriterion("SC_CREATE_TIME in", values, "scCreateTime");
            return (Criteria) this;
        }

        public Criteria andScCreateTimeNotIn(List<Date> values) {
            addCriterion("SC_CREATE_TIME not in", values, "scCreateTime");
            return (Criteria) this;
        }

        public Criteria andScCreateTimeBetween(Date value1, Date value2) {
            addCriterion("SC_CREATE_TIME between", value1, value2, "scCreateTime");
            return (Criteria) this;
        }

        public Criteria andScCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("SC_CREATE_TIME not between", value1, value2, "scCreateTime");
            return (Criteria) this;
        }

        public Criteria andScNickNameIsNull() {
            addCriterion("SC_NICK_NAME is null");
            return (Criteria) this;
        }

        public Criteria andScNickNameIsNotNull() {
            addCriterion("SC_NICK_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andScNickNameEqualTo(String value) {
            addCriterion("SC_NICK_NAME =", value, "scNickName");
            return (Criteria) this;
        }

        public Criteria andScNickNameNotEqualTo(String value) {
            addCriterion("SC_NICK_NAME <>", value, "scNickName");
            return (Criteria) this;
        }

        public Criteria andScNickNameGreaterThan(String value) {
            addCriterion("SC_NICK_NAME >", value, "scNickName");
            return (Criteria) this;
        }

        public Criteria andScNickNameGreaterThanOrEqualTo(String value) {
            addCriterion("SC_NICK_NAME >=", value, "scNickName");
            return (Criteria) this;
        }

        public Criteria andScNickNameLessThan(String value) {
            addCriterion("SC_NICK_NAME <", value, "scNickName");
            return (Criteria) this;
        }

        public Criteria andScNickNameLessThanOrEqualTo(String value) {
            addCriterion("SC_NICK_NAME <=", value, "scNickName");
            return (Criteria) this;
        }

        public Criteria andScNickNameLike(String value) {
            addCriterion("SC_NICK_NAME like", value, "scNickName");
            return (Criteria) this;
        }

        public Criteria andScNickNameNotLike(String value) {
            addCriterion("SC_NICK_NAME not like", value, "scNickName");
            return (Criteria) this;
        }

        public Criteria andScNickNameIn(List<String> values) {
            addCriterion("SC_NICK_NAME in", values, "scNickName");
            return (Criteria) this;
        }

        public Criteria andScNickNameNotIn(List<String> values) {
            addCriterion("SC_NICK_NAME not in", values, "scNickName");
            return (Criteria) this;
        }

        public Criteria andScNickNameBetween(String value1, String value2) {
            addCriterion("SC_NICK_NAME between", value1, value2, "scNickName");
            return (Criteria) this;
        }

        public Criteria andScNickNameNotBetween(String value1, String value2) {
            addCriterion("SC_NICK_NAME not between", value1, value2, "scNickName");
            return (Criteria) this;
        }

        public Criteria andScSpIdIsNull() {
            addCriterion("SC_SP_ID is null");
            return (Criteria) this;
        }

        public Criteria andScSpIdIsNotNull() {
            addCriterion("SC_SP_ID is not null");
            return (Criteria) this;
        }

        public Criteria andScSpIdEqualTo(Integer value) {
            addCriterion("SC_SP_ID =", value, "scSpId");
            return (Criteria) this;
        }

        public Criteria andScSpIdNotEqualTo(Integer value) {
            addCriterion("SC_SP_ID <>", value, "scSpId");
            return (Criteria) this;
        }

        public Criteria andScSpIdGreaterThan(Integer value) {
            addCriterion("SC_SP_ID >", value, "scSpId");
            return (Criteria) this;
        }

        public Criteria andScSpIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("SC_SP_ID >=", value, "scSpId");
            return (Criteria) this;
        }

        public Criteria andScSpIdLessThan(Integer value) {
            addCriterion("SC_SP_ID <", value, "scSpId");
            return (Criteria) this;
        }

        public Criteria andScSpIdLessThanOrEqualTo(Integer value) {
            addCriterion("SC_SP_ID <=", value, "scSpId");
            return (Criteria) this;
        }

        public Criteria andScSpIdIn(List<Integer> values) {
            addCriterion("SC_SP_ID in", values, "scSpId");
            return (Criteria) this;
        }

        public Criteria andScSpIdNotIn(List<Integer> values) {
            addCriterion("SC_SP_ID not in", values, "scSpId");
            return (Criteria) this;
        }

        public Criteria andScSpIdBetween(Integer value1, Integer value2) {
            addCriterion("SC_SP_ID between", value1, value2, "scSpId");
            return (Criteria) this;
        }

        public Criteria andScSpIdNotBetween(Integer value1, Integer value2) {
            addCriterion("SC_SP_ID not between", value1, value2, "scSpId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sm_comment
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sm_comment
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}