package com.cn.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SmOrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sm_order
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sm_order
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sm_order
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_order
     *
     * @mbg.generated
     */
    public SmOrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_order
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_order
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_order
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_order
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_order
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_order
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_order
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_order
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_order
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_order
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sm_order
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSoIdIsNull() {
            addCriterion("so_id is null");
            return (Criteria) this;
        }

        public Criteria andSoIdIsNotNull() {
            addCriterion("so_id is not null");
            return (Criteria) this;
        }

        public Criteria andSoIdEqualTo(Integer value) {
            addCriterion("so_id =", value, "soId");
            return (Criteria) this;
        }

        public Criteria andSoIdNotEqualTo(Integer value) {
            addCriterion("so_id <>", value, "soId");
            return (Criteria) this;
        }

        public Criteria andSoIdGreaterThan(Integer value) {
            addCriterion("so_id >", value, "soId");
            return (Criteria) this;
        }

        public Criteria andSoIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("so_id >=", value, "soId");
            return (Criteria) this;
        }

        public Criteria andSoIdLessThan(Integer value) {
            addCriterion("so_id <", value, "soId");
            return (Criteria) this;
        }

        public Criteria andSoIdLessThanOrEqualTo(Integer value) {
            addCriterion("so_id <=", value, "soId");
            return (Criteria) this;
        }

        public Criteria andSoIdIn(List<Integer> values) {
            addCriterion("so_id in", values, "soId");
            return (Criteria) this;
        }

        public Criteria andSoIdNotIn(List<Integer> values) {
            addCriterion("so_id not in", values, "soId");
            return (Criteria) this;
        }

        public Criteria andSoIdBetween(Integer value1, Integer value2) {
            addCriterion("so_id between", value1, value2, "soId");
            return (Criteria) this;
        }

        public Criteria andSoIdNotBetween(Integer value1, Integer value2) {
            addCriterion("so_id not between", value1, value2, "soId");
            return (Criteria) this;
        }

        public Criteria andSoUserNameIsNull() {
            addCriterion("so_user_name is null");
            return (Criteria) this;
        }

        public Criteria andSoUserNameIsNotNull() {
            addCriterion("so_user_name is not null");
            return (Criteria) this;
        }

        public Criteria andSoUserNameEqualTo(String value) {
            addCriterion("so_user_name =", value, "soUserName");
            return (Criteria) this;
        }

        public Criteria andSoUserNameNotEqualTo(String value) {
            addCriterion("so_user_name <>", value, "soUserName");
            return (Criteria) this;
        }

        public Criteria andSoUserNameGreaterThan(String value) {
            addCriterion("so_user_name >", value, "soUserName");
            return (Criteria) this;
        }

        public Criteria andSoUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("so_user_name >=", value, "soUserName");
            return (Criteria) this;
        }

        public Criteria andSoUserNameLessThan(String value) {
            addCriterion("so_user_name <", value, "soUserName");
            return (Criteria) this;
        }

        public Criteria andSoUserNameLessThanOrEqualTo(String value) {
            addCriterion("so_user_name <=", value, "soUserName");
            return (Criteria) this;
        }

        public Criteria andSoUserNameLike(String value) {
            addCriterion("so_user_name like", value, "soUserName");
            return (Criteria) this;
        }

        public Criteria andSoUserNameNotLike(String value) {
            addCriterion("so_user_name not like", value, "soUserName");
            return (Criteria) this;
        }

        public Criteria andSoUserNameIn(List<String> values) {
            addCriterion("so_user_name in", values, "soUserName");
            return (Criteria) this;
        }

        public Criteria andSoUserNameNotIn(List<String> values) {
            addCriterion("so_user_name not in", values, "soUserName");
            return (Criteria) this;
        }

        public Criteria andSoUserNameBetween(String value1, String value2) {
            addCriterion("so_user_name between", value1, value2, "soUserName");
            return (Criteria) this;
        }

        public Criteria andSoUserNameNotBetween(String value1, String value2) {
            addCriterion("so_user_name not between", value1, value2, "soUserName");
            return (Criteria) this;
        }

        public Criteria andSoUserAddressIsNull() {
            addCriterion("so_user_address is null");
            return (Criteria) this;
        }

        public Criteria andSoUserAddressIsNotNull() {
            addCriterion("so_user_address is not null");
            return (Criteria) this;
        }

        public Criteria andSoUserAddressEqualTo(String value) {
            addCriterion("so_user_address =", value, "soUserAddress");
            return (Criteria) this;
        }

        public Criteria andSoUserAddressNotEqualTo(String value) {
            addCriterion("so_user_address <>", value, "soUserAddress");
            return (Criteria) this;
        }

        public Criteria andSoUserAddressGreaterThan(String value) {
            addCriterion("so_user_address >", value, "soUserAddress");
            return (Criteria) this;
        }

        public Criteria andSoUserAddressGreaterThanOrEqualTo(String value) {
            addCriterion("so_user_address >=", value, "soUserAddress");
            return (Criteria) this;
        }

        public Criteria andSoUserAddressLessThan(String value) {
            addCriterion("so_user_address <", value, "soUserAddress");
            return (Criteria) this;
        }

        public Criteria andSoUserAddressLessThanOrEqualTo(String value) {
            addCriterion("so_user_address <=", value, "soUserAddress");
            return (Criteria) this;
        }

        public Criteria andSoUserAddressLike(String value) {
            addCriterion("so_user_address like", value, "soUserAddress");
            return (Criteria) this;
        }

        public Criteria andSoUserAddressNotLike(String value) {
            addCriterion("so_user_address not like", value, "soUserAddress");
            return (Criteria) this;
        }

        public Criteria andSoUserAddressIn(List<String> values) {
            addCriterion("so_user_address in", values, "soUserAddress");
            return (Criteria) this;
        }

        public Criteria andSoUserAddressNotIn(List<String> values) {
            addCriterion("so_user_address not in", values, "soUserAddress");
            return (Criteria) this;
        }

        public Criteria andSoUserAddressBetween(String value1, String value2) {
            addCriterion("so_user_address between", value1, value2, "soUserAddress");
            return (Criteria) this;
        }

        public Criteria andSoUserAddressNotBetween(String value1, String value2) {
            addCriterion("so_user_address not between", value1, value2, "soUserAddress");
            return (Criteria) this;
        }

        public Criteria andSoNameIsNull() {
            addCriterion("so_name is null");
            return (Criteria) this;
        }

        public Criteria andSoNameIsNotNull() {
            addCriterion("so_name is not null");
            return (Criteria) this;
        }

        public Criteria andSoNameEqualTo(String value) {
            addCriterion("so_name =", value, "soName");
            return (Criteria) this;
        }

        public Criteria andSoNameNotEqualTo(String value) {
            addCriterion("so_name <>", value, "soName");
            return (Criteria) this;
        }

        public Criteria andSoNameGreaterThan(String value) {
            addCriterion("so_name >", value, "soName");
            return (Criteria) this;
        }

        public Criteria andSoNameGreaterThanOrEqualTo(String value) {
            addCriterion("so_name >=", value, "soName");
            return (Criteria) this;
        }

        public Criteria andSoNameLessThan(String value) {
            addCriterion("so_name <", value, "soName");
            return (Criteria) this;
        }

        public Criteria andSoNameLessThanOrEqualTo(String value) {
            addCriterion("so_name <=", value, "soName");
            return (Criteria) this;
        }

        public Criteria andSoNameLike(String value) {
            addCriterion("so_name like", value, "soName");
            return (Criteria) this;
        }

        public Criteria andSoNameNotLike(String value) {
            addCriterion("so_name not like", value, "soName");
            return (Criteria) this;
        }

        public Criteria andSoNameIn(List<String> values) {
            addCriterion("so_name in", values, "soName");
            return (Criteria) this;
        }

        public Criteria andSoNameNotIn(List<String> values) {
            addCriterion("so_name not in", values, "soName");
            return (Criteria) this;
        }

        public Criteria andSoNameBetween(String value1, String value2) {
            addCriterion("so_name between", value1, value2, "soName");
            return (Criteria) this;
        }

        public Criteria andSoNameNotBetween(String value1, String value2) {
            addCriterion("so_name not between", value1, value2, "soName");
            return (Criteria) this;
        }

        public Criteria andSoCreateTimeIsNull() {
            addCriterion("so_create_time is null");
            return (Criteria) this;
        }

        public Criteria andSoCreateTimeIsNotNull() {
            addCriterion("so_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andSoCreateTimeEqualTo(Date value) {
            addCriterion("so_create_time =", value, "soCreateTime");
            return (Criteria) this;
        }

        public Criteria andSoCreateTimeNotEqualTo(Date value) {
            addCriterion("so_create_time <>", value, "soCreateTime");
            return (Criteria) this;
        }

        public Criteria andSoCreateTimeGreaterThan(Date value) {
            addCriterion("so_create_time >", value, "soCreateTime");
            return (Criteria) this;
        }

        public Criteria andSoCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("so_create_time >=", value, "soCreateTime");
            return (Criteria) this;
        }

        public Criteria andSoCreateTimeLessThan(Date value) {
            addCriterion("so_create_time <", value, "soCreateTime");
            return (Criteria) this;
        }

        public Criteria andSoCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("so_create_time <=", value, "soCreateTime");
            return (Criteria) this;
        }

        public Criteria andSoCreateTimeIn(List<Date> values) {
            addCriterion("so_create_time in", values, "soCreateTime");
            return (Criteria) this;
        }

        public Criteria andSoCreateTimeNotIn(List<Date> values) {
            addCriterion("so_create_time not in", values, "soCreateTime");
            return (Criteria) this;
        }

        public Criteria andSoCreateTimeBetween(Date value1, Date value2) {
            addCriterion("so_create_time between", value1, value2, "soCreateTime");
            return (Criteria) this;
        }

        public Criteria andSoCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("so_create_time not between", value1, value2, "soCreateTime");
            return (Criteria) this;
        }

        public Criteria andSodQuantityIsNull() {
            addCriterion("sod_quantity is null");
            return (Criteria) this;
        }

        public Criteria andSodQuantityIsNotNull() {
            addCriterion("sod_quantity is not null");
            return (Criteria) this;
        }

        public Criteria andSodQuantityEqualTo(Integer value) {
            addCriterion("sod_quantity =", value, "sodQuantity");
            return (Criteria) this;
        }

        public Criteria andSodQuantityNotEqualTo(Integer value) {
            addCriterion("sod_quantity <>", value, "sodQuantity");
            return (Criteria) this;
        }

        public Criteria andSodQuantityGreaterThan(Integer value) {
            addCriterion("sod_quantity >", value, "sodQuantity");
            return (Criteria) this;
        }

        public Criteria andSodQuantityGreaterThanOrEqualTo(Integer value) {
            addCriterion("sod_quantity >=", value, "sodQuantity");
            return (Criteria) this;
        }

        public Criteria andSodQuantityLessThan(Integer value) {
            addCriterion("sod_quantity <", value, "sodQuantity");
            return (Criteria) this;
        }

        public Criteria andSodQuantityLessThanOrEqualTo(Integer value) {
            addCriterion("sod_quantity <=", value, "sodQuantity");
            return (Criteria) this;
        }

        public Criteria andSodQuantityIn(List<Integer> values) {
            addCriterion("sod_quantity in", values, "sodQuantity");
            return (Criteria) this;
        }

        public Criteria andSodQuantityNotIn(List<Integer> values) {
            addCriterion("sod_quantity not in", values, "sodQuantity");
            return (Criteria) this;
        }

        public Criteria andSodQuantityBetween(Integer value1, Integer value2) {
            addCriterion("sod_quantity between", value1, value2, "sodQuantity");
            return (Criteria) this;
        }

        public Criteria andSodQuantityNotBetween(Integer value1, Integer value2) {
            addCriterion("sod_quantity not between", value1, value2, "sodQuantity");
            return (Criteria) this;
        }

        public Criteria andSoCostIsNull() {
            addCriterion("so_cost is null");
            return (Criteria) this;
        }

        public Criteria andSoCostIsNotNull() {
            addCriterion("so_cost is not null");
            return (Criteria) this;
        }

        public Criteria andSoCostEqualTo(BigDecimal value) {
            addCriterion("so_cost =", value, "soCost");
            return (Criteria) this;
        }

        public Criteria andSoCostNotEqualTo(BigDecimal value) {
            addCriterion("so_cost <>", value, "soCost");
            return (Criteria) this;
        }

        public Criteria andSoCostGreaterThan(BigDecimal value) {
            addCriterion("so_cost >", value, "soCost");
            return (Criteria) this;
        }

        public Criteria andSoCostGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("so_cost >=", value, "soCost");
            return (Criteria) this;
        }

        public Criteria andSoCostLessThan(BigDecimal value) {
            addCriterion("so_cost <", value, "soCost");
            return (Criteria) this;
        }

        public Criteria andSoCostLessThanOrEqualTo(BigDecimal value) {
            addCriterion("so_cost <=", value, "soCost");
            return (Criteria) this;
        }

        public Criteria andSoCostIn(List<BigDecimal> values) {
            addCriterion("so_cost in", values, "soCost");
            return (Criteria) this;
        }

        public Criteria andSoCostNotIn(List<BigDecimal> values) {
            addCriterion("so_cost not in", values, "soCost");
            return (Criteria) this;
        }

        public Criteria andSoCostBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("so_cost between", value1, value2, "soCost");
            return (Criteria) this;
        }

        public Criteria andSoCostNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("so_cost not between", value1, value2, "soCost");
            return (Criteria) this;
        }

        public Criteria andSoStatusIsNull() {
            addCriterion("so_status is null");
            return (Criteria) this;
        }

        public Criteria andSoStatusIsNotNull() {
            addCriterion("so_status is not null");
            return (Criteria) this;
        }

        public Criteria andSoStatusEqualTo(Integer value) {
            addCriterion("so_status =", value, "soStatus");
            return (Criteria) this;
        }

        public Criteria andSoStatusNotEqualTo(Integer value) {
            addCriterion("so_status <>", value, "soStatus");
            return (Criteria) this;
        }

        public Criteria andSoStatusGreaterThan(Integer value) {
            addCriterion("so_status >", value, "soStatus");
            return (Criteria) this;
        }

        public Criteria andSoStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("so_status >=", value, "soStatus");
            return (Criteria) this;
        }

        public Criteria andSoStatusLessThan(Integer value) {
            addCriterion("so_status <", value, "soStatus");
            return (Criteria) this;
        }

        public Criteria andSoStatusLessThanOrEqualTo(Integer value) {
            addCriterion("so_status <=", value, "soStatus");
            return (Criteria) this;
        }

        public Criteria andSoStatusIn(List<Integer> values) {
            addCriterion("so_status in", values, "soStatus");
            return (Criteria) this;
        }

        public Criteria andSoStatusNotIn(List<Integer> values) {
            addCriterion("so_status not in", values, "soStatus");
            return (Criteria) this;
        }

        public Criteria andSoStatusBetween(Integer value1, Integer value2) {
            addCriterion("so_status between", value1, value2, "soStatus");
            return (Criteria) this;
        }

        public Criteria andSoStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("so_status not between", value1, value2, "soStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sm_order
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sm_order
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}