package com.cn.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class SmProduct implements Serializable {

    private Integer count =1;//购物车计数

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_product.sp_id
     *
     * @mbg.generated
     */
    private Integer spId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_product.sp_name
     *
     * @mbg.generated
     */
    private String spName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_product.sp_description
     *
     * @mbg.generated
     */
    private String spDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_product.sp_price
     *
     * @mbg.generated
     */
    private BigDecimal spPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_product.sp_stock
     *
     * @mbg.generated
     */
    private Integer spStock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_product.spc_child_id
     *
     * @mbg.generated
     */
    private Integer spcChildId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_product.sp_file_name
     *
     * @mbg.generated
     */
    private String spFileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sm_product
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_product.sp_id
     *
     * @return the value of sm_product.sp_id
     *
     * @mbg.generated
     */
    public Integer getSpId() {
        return spId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_product.sp_id
     *
     * @param spId the value for sm_product.sp_id
     *
     * @mbg.generated
     */
    public void setSpId(Integer spId) {
        this.spId = spId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_product.sp_name
     *
     * @return the value of sm_product.sp_name
     *
     * @mbg.generated
     */
    public String getSpName() {
        return spName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_product.sp_name
     *
     * @param spName the value for sm_product.sp_name
     *
     * @mbg.generated
     */
    public void setSpName(String spName) {
        this.spName = spName == null ? null : spName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_product.sp_description
     *
     * @return the value of sm_product.sp_description
     *
     * @mbg.generated
     */
    public String getSpDescription() {
        return spDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_product.sp_description
     *
     * @param spDescription the value for sm_product.sp_description
     *
     * @mbg.generated
     */
    public void setSpDescription(String spDescription) {
        this.spDescription = spDescription == null ? null : spDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_product.sp_price
     *
     * @return the value of sm_product.sp_price
     *
     * @mbg.generated
     */
    public BigDecimal getSpPrice() {
        return spPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_product.sp_price
     *
     * @param spPrice the value for sm_product.sp_price
     *
     * @mbg.generated
     */
    public void setSpPrice(BigDecimal spPrice) {
        this.spPrice = spPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_product.sp_stock
     *
     * @return the value of sm_product.sp_stock
     *
     * @mbg.generated
     */
    public Integer getSpStock() {
        return spStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_product.sp_stock
     *
     * @param spStock the value for sm_product.sp_stock
     *
     * @mbg.generated
     */
    public void setSpStock(Integer spStock) {
        this.spStock = spStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_product.spc_child_id
     *
     * @return the value of sm_product.spc_child_id
     *
     * @mbg.generated
     */
    public Integer getSpcChildId() {
        return spcChildId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_product.spc_child_id
     *
     * @param spcChildId the value for sm_product.spc_child_id
     *
     * @mbg.generated
     */
    public void setSpcChildId(Integer spcChildId) {
        this.spcChildId = spcChildId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_product.sp_file_name
     *
     * @return the value of sm_product.sp_file_name
     *
     * @mbg.generated
     */
    public String getSpFileName() {
        return spFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_product.sp_file_name
     *
     * @param spFileName the value for sm_product.sp_file_name
     *
     * @mbg.generated
     */
    public void setSpFileName(String spFileName) {
        this.spFileName = spFileName == null ? null : spFileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_product
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", spId=").append(spId);
        sb.append(", spName=").append(spName);
        sb.append(", spDescription=").append(spDescription);
        sb.append(", spPrice=").append(spPrice);
        sb.append(", spStock=").append(spStock);
        sb.append(", spcChildId=").append(spcChildId);
        sb.append(", spFileName=").append(spFileName);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_product
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SmProduct other = (SmProduct) that;
        return (this.getSpId() == null ? other.getSpId() == null : this.getSpId().equals(other.getSpId()))
            && (this.getSpName() == null ? other.getSpName() == null : this.getSpName().equals(other.getSpName()))
            && (this.getSpDescription() == null ? other.getSpDescription() == null : this.getSpDescription().equals(other.getSpDescription()))
            && (this.getSpPrice() == null ? other.getSpPrice() == null : this.getSpPrice().equals(other.getSpPrice()))
            && (this.getSpStock() == null ? other.getSpStock() == null : this.getSpStock().equals(other.getSpStock()))
            && (this.getSpcChildId() == null ? other.getSpcChildId() == null : this.getSpcChildId().equals(other.getSpcChildId()))
            && (this.getSpFileName() == null ? other.getSpFileName() == null : this.getSpFileName().equals(other.getSpFileName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_product
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSpId() == null) ? 0 : getSpId().hashCode());
        result = prime * result + ((getSpName() == null) ? 0 : getSpName().hashCode());
        result = prime * result + ((getSpDescription() == null) ? 0 : getSpDescription().hashCode());
        result = prime * result + ((getSpPrice() == null) ? 0 : getSpPrice().hashCode());
        result = prime * result + ((getSpStock() == null) ? 0 : getSpStock().hashCode());
        result = prime * result + ((getSpcChildId() == null) ? 0 : getSpcChildId().hashCode());
        result = prime * result + ((getSpFileName() == null) ? 0 : getSpFileName().hashCode());
        return result;
    }
}