package com.cn.model;

import java.io.Serializable;

public class SmProductCategory implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_product_category.SPC_ID
     *
     * @mbg.generated
     */
    private Integer spcId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_product_category.SPC_NAME
     *
     * @mbg.generated
     */
    private String spcName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_product_category.SPC_PARENT_ID
     *
     * @mbg.generated
     */
    private Integer spcParentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sm_product_category
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_product_category.SPC_ID
     *
     * @return the value of sm_product_category.SPC_ID
     *
     * @mbg.generated
     */
    public Integer getSpcId() {
        return spcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_product_category.SPC_ID
     *
     * @param spcId the value for sm_product_category.SPC_ID
     *
     * @mbg.generated
     */
    public void setSpcId(Integer spcId) {
        this.spcId = spcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_product_category.SPC_NAME
     *
     * @return the value of sm_product_category.SPC_NAME
     *
     * @mbg.generated
     */
    public String getSpcName() {
        return spcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_product_category.SPC_NAME
     *
     * @param spcName the value for sm_product_category.SPC_NAME
     *
     * @mbg.generated
     */
    public void setSpcName(String spcName) {
        this.spcName = spcName == null ? null : spcName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_product_category.SPC_PARENT_ID
     *
     * @return the value of sm_product_category.SPC_PARENT_ID
     *
     * @mbg.generated
     */
    public Integer getSpcParentId() {
        return spcParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_product_category.SPC_PARENT_ID
     *
     * @param spcParentId the value for sm_product_category.SPC_PARENT_ID
     *
     * @mbg.generated
     */
    public void setSpcParentId(Integer spcParentId) {
        this.spcParentId = spcParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_product_category
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", spcId=").append(spcId);
        sb.append(", spcName=").append(spcName);
        sb.append(", spcParentId=").append(spcParentId);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_product_category
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SmProductCategory other = (SmProductCategory) that;
        return (this.getSpcId() == null ? other.getSpcId() == null : this.getSpcId().equals(other.getSpcId()))
            && (this.getSpcName() == null ? other.getSpcName() == null : this.getSpcName().equals(other.getSpcName()))
            && (this.getSpcParentId() == null ? other.getSpcParentId() == null : this.getSpcParentId().equals(other.getSpcParentId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_product_category
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSpcId() == null) ? 0 : getSpcId().hashCode());
        result = prime * result + ((getSpcName() == null) ? 0 : getSpcName().hashCode());
        result = prime * result + ((getSpcParentId() == null) ? 0 : getSpcParentId().hashCode());
        return result;
    }
}