package com.cn.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class SmProductExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sm_product
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sm_product
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sm_product
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_product
     *
     * @mbg.generated
     */
    public SmProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_product
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_product
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_product
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_product
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_product
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_product
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_product
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_product
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_product
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_product
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sm_product
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSpIdIsNull() {
            addCriterion("sp_id is null");
            return (Criteria) this;
        }

        public Criteria andSpIdIsNotNull() {
            addCriterion("sp_id is not null");
            return (Criteria) this;
        }

        public Criteria andSpIdEqualTo(Integer value) {
            addCriterion("sp_id =", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdNotEqualTo(Integer value) {
            addCriterion("sp_id <>", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdGreaterThan(Integer value) {
            addCriterion("sp_id >", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("sp_id >=", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdLessThan(Integer value) {
            addCriterion("sp_id <", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdLessThanOrEqualTo(Integer value) {
            addCriterion("sp_id <=", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdIn(List<Integer> values) {
            addCriterion("sp_id in", values, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdNotIn(List<Integer> values) {
            addCriterion("sp_id not in", values, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdBetween(Integer value1, Integer value2) {
            addCriterion("sp_id between", value1, value2, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdNotBetween(Integer value1, Integer value2) {
            addCriterion("sp_id not between", value1, value2, "spId");
            return (Criteria) this;
        }

        public Criteria andSpNameIsNull() {
            addCriterion("sp_name is null");
            return (Criteria) this;
        }

        public Criteria andSpNameIsNotNull() {
            addCriterion("sp_name is not null");
            return (Criteria) this;
        }

        public Criteria andSpNameEqualTo(String value) {
            addCriterion("sp_name =", value, "spName");
            return (Criteria) this;
        }

        public Criteria andSpNameNotEqualTo(String value) {
            addCriterion("sp_name <>", value, "spName");
            return (Criteria) this;
        }

        public Criteria andSpNameGreaterThan(String value) {
            addCriterion("sp_name >", value, "spName");
            return (Criteria) this;
        }

        public Criteria andSpNameGreaterThanOrEqualTo(String value) {
            addCriterion("sp_name >=", value, "spName");
            return (Criteria) this;
        }

        public Criteria andSpNameLessThan(String value) {
            addCriterion("sp_name <", value, "spName");
            return (Criteria) this;
        }

        public Criteria andSpNameLessThanOrEqualTo(String value) {
            addCriterion("sp_name <=", value, "spName");
            return (Criteria) this;
        }

        public Criteria andSpNameLike(String value) {
            addCriterion("sp_name like", value, "spName");
            return (Criteria) this;
        }

        public Criteria andSpNameNotLike(String value) {
            addCriterion("sp_name not like", value, "spName");
            return (Criteria) this;
        }

        public Criteria andSpNameIn(List<String> values) {
            addCriterion("sp_name in", values, "spName");
            return (Criteria) this;
        }

        public Criteria andSpNameNotIn(List<String> values) {
            addCriterion("sp_name not in", values, "spName");
            return (Criteria) this;
        }

        public Criteria andSpNameBetween(String value1, String value2) {
            addCriterion("sp_name between", value1, value2, "spName");
            return (Criteria) this;
        }

        public Criteria andSpNameNotBetween(String value1, String value2) {
            addCriterion("sp_name not between", value1, value2, "spName");
            return (Criteria) this;
        }

        public Criteria andSpDescriptionIsNull() {
            addCriterion("sp_description is null");
            return (Criteria) this;
        }

        public Criteria andSpDescriptionIsNotNull() {
            addCriterion("sp_description is not null");
            return (Criteria) this;
        }

        public Criteria andSpDescriptionEqualTo(String value) {
            addCriterion("sp_description =", value, "spDescription");
            return (Criteria) this;
        }

        public Criteria andSpDescriptionNotEqualTo(String value) {
            addCriterion("sp_description <>", value, "spDescription");
            return (Criteria) this;
        }

        public Criteria andSpDescriptionGreaterThan(String value) {
            addCriterion("sp_description >", value, "spDescription");
            return (Criteria) this;
        }

        public Criteria andSpDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("sp_description >=", value, "spDescription");
            return (Criteria) this;
        }

        public Criteria andSpDescriptionLessThan(String value) {
            addCriterion("sp_description <", value, "spDescription");
            return (Criteria) this;
        }

        public Criteria andSpDescriptionLessThanOrEqualTo(String value) {
            addCriterion("sp_description <=", value, "spDescription");
            return (Criteria) this;
        }

        public Criteria andSpDescriptionLike(String value) {
            addCriterion("sp_description like", value, "spDescription");
            return (Criteria) this;
        }

        public Criteria andSpDescriptionNotLike(String value) {
            addCriterion("sp_description not like", value, "spDescription");
            return (Criteria) this;
        }

        public Criteria andSpDescriptionIn(List<String> values) {
            addCriterion("sp_description in", values, "spDescription");
            return (Criteria) this;
        }

        public Criteria andSpDescriptionNotIn(List<String> values) {
            addCriterion("sp_description not in", values, "spDescription");
            return (Criteria) this;
        }

        public Criteria andSpDescriptionBetween(String value1, String value2) {
            addCriterion("sp_description between", value1, value2, "spDescription");
            return (Criteria) this;
        }

        public Criteria andSpDescriptionNotBetween(String value1, String value2) {
            addCriterion("sp_description not between", value1, value2, "spDescription");
            return (Criteria) this;
        }

        public Criteria andSpPriceIsNull() {
            addCriterion("sp_price is null");
            return (Criteria) this;
        }

        public Criteria andSpPriceIsNotNull() {
            addCriterion("sp_price is not null");
            return (Criteria) this;
        }

        public Criteria andSpPriceEqualTo(BigDecimal value) {
            addCriterion("sp_price =", value, "spPrice");
            return (Criteria) this;
        }

        public Criteria andSpPriceNotEqualTo(BigDecimal value) {
            addCriterion("sp_price <>", value, "spPrice");
            return (Criteria) this;
        }

        public Criteria andSpPriceGreaterThan(BigDecimal value) {
            addCriterion("sp_price >", value, "spPrice");
            return (Criteria) this;
        }

        public Criteria andSpPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("sp_price >=", value, "spPrice");
            return (Criteria) this;
        }

        public Criteria andSpPriceLessThan(BigDecimal value) {
            addCriterion("sp_price <", value, "spPrice");
            return (Criteria) this;
        }

        public Criteria andSpPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("sp_price <=", value, "spPrice");
            return (Criteria) this;
        }

        public Criteria andSpPriceIn(List<BigDecimal> values) {
            addCriterion("sp_price in", values, "spPrice");
            return (Criteria) this;
        }

        public Criteria andSpPriceNotIn(List<BigDecimal> values) {
            addCriterion("sp_price not in", values, "spPrice");
            return (Criteria) this;
        }

        public Criteria andSpPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sp_price between", value1, value2, "spPrice");
            return (Criteria) this;
        }

        public Criteria andSpPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sp_price not between", value1, value2, "spPrice");
            return (Criteria) this;
        }

        public Criteria andSpStockIsNull() {
            addCriterion("sp_stock is null");
            return (Criteria) this;
        }

        public Criteria andSpStockIsNotNull() {
            addCriterion("sp_stock is not null");
            return (Criteria) this;
        }

        public Criteria andSpStockEqualTo(Integer value) {
            addCriterion("sp_stock =", value, "spStock");
            return (Criteria) this;
        }

        public Criteria andSpStockNotEqualTo(Integer value) {
            addCriterion("sp_stock <>", value, "spStock");
            return (Criteria) this;
        }

        public Criteria andSpStockGreaterThan(Integer value) {
            addCriterion("sp_stock >", value, "spStock");
            return (Criteria) this;
        }

        public Criteria andSpStockGreaterThanOrEqualTo(Integer value) {
            addCriterion("sp_stock >=", value, "spStock");
            return (Criteria) this;
        }

        public Criteria andSpStockLessThan(Integer value) {
            addCriterion("sp_stock <", value, "spStock");
            return (Criteria) this;
        }

        public Criteria andSpStockLessThanOrEqualTo(Integer value) {
            addCriterion("sp_stock <=", value, "spStock");
            return (Criteria) this;
        }

        public Criteria andSpStockIn(List<Integer> values) {
            addCriterion("sp_stock in", values, "spStock");
            return (Criteria) this;
        }

        public Criteria andSpStockNotIn(List<Integer> values) {
            addCriterion("sp_stock not in", values, "spStock");
            return (Criteria) this;
        }

        public Criteria andSpStockBetween(Integer value1, Integer value2) {
            addCriterion("sp_stock between", value1, value2, "spStock");
            return (Criteria) this;
        }

        public Criteria andSpStockNotBetween(Integer value1, Integer value2) {
            addCriterion("sp_stock not between", value1, value2, "spStock");
            return (Criteria) this;
        }

        public Criteria andSpcChildIdIsNull() {
            addCriterion("spc_child_id is null");
            return (Criteria) this;
        }

        public Criteria andSpcChildIdIsNotNull() {
            addCriterion("spc_child_id is not null");
            return (Criteria) this;
        }

        public Criteria andSpcChildIdEqualTo(Integer value) {
            addCriterion("spc_child_id =", value, "spcChildId");
            return (Criteria) this;
        }

        public Criteria andSpcChildIdNotEqualTo(Integer value) {
            addCriterion("spc_child_id <>", value, "spcChildId");
            return (Criteria) this;
        }

        public Criteria andSpcChildIdGreaterThan(Integer value) {
            addCriterion("spc_child_id >", value, "spcChildId");
            return (Criteria) this;
        }

        public Criteria andSpcChildIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("spc_child_id >=", value, "spcChildId");
            return (Criteria) this;
        }

        public Criteria andSpcChildIdLessThan(Integer value) {
            addCriterion("spc_child_id <", value, "spcChildId");
            return (Criteria) this;
        }

        public Criteria andSpcChildIdLessThanOrEqualTo(Integer value) {
            addCriterion("spc_child_id <=", value, "spcChildId");
            return (Criteria) this;
        }

        public Criteria andSpcChildIdIn(List<Integer> values) {
            addCriterion("spc_child_id in", values, "spcChildId");
            return (Criteria) this;
        }

        public Criteria andSpcChildIdNotIn(List<Integer> values) {
            addCriterion("spc_child_id not in", values, "spcChildId");
            return (Criteria) this;
        }

        public Criteria andSpcChildIdBetween(Integer value1, Integer value2) {
            addCriterion("spc_child_id between", value1, value2, "spcChildId");
            return (Criteria) this;
        }

        public Criteria andSpcChildIdNotBetween(Integer value1, Integer value2) {
            addCriterion("spc_child_id not between", value1, value2, "spcChildId");
            return (Criteria) this;
        }

        public Criteria andSpFileNameIsNull() {
            addCriterion("sp_file_name is null");
            return (Criteria) this;
        }

        public Criteria andSpFileNameIsNotNull() {
            addCriterion("sp_file_name is not null");
            return (Criteria) this;
        }

        public Criteria andSpFileNameEqualTo(String value) {
            addCriterion("sp_file_name =", value, "spFileName");
            return (Criteria) this;
        }

        public Criteria andSpFileNameNotEqualTo(String value) {
            addCriterion("sp_file_name <>", value, "spFileName");
            return (Criteria) this;
        }

        public Criteria andSpFileNameGreaterThan(String value) {
            addCriterion("sp_file_name >", value, "spFileName");
            return (Criteria) this;
        }

        public Criteria andSpFileNameGreaterThanOrEqualTo(String value) {
            addCriterion("sp_file_name >=", value, "spFileName");
            return (Criteria) this;
        }

        public Criteria andSpFileNameLessThan(String value) {
            addCriterion("sp_file_name <", value, "spFileName");
            return (Criteria) this;
        }

        public Criteria andSpFileNameLessThanOrEqualTo(String value) {
            addCriterion("sp_file_name <=", value, "spFileName");
            return (Criteria) this;
        }

        public Criteria andSpFileNameLike(String value) {
            addCriterion("sp_file_name like", value, "spFileName");
            return (Criteria) this;
        }

        public Criteria andSpFileNameNotLike(String value) {
            addCriterion("sp_file_name not like", value, "spFileName");
            return (Criteria) this;
        }

        public Criteria andSpFileNameIn(List<String> values) {
            addCriterion("sp_file_name in", values, "spFileName");
            return (Criteria) this;
        }

        public Criteria andSpFileNameNotIn(List<String> values) {
            addCriterion("sp_file_name not in", values, "spFileName");
            return (Criteria) this;
        }

        public Criteria andSpFileNameBetween(String value1, String value2) {
            addCriterion("sp_file_name between", value1, value2, "spFileName");
            return (Criteria) this;
        }

        public Criteria andSpFileNameNotBetween(String value1, String value2) {
            addCriterion("sp_file_name not between", value1, value2, "spFileName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sm_product
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sm_product
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}