package com.cn.model;

import java.util.ArrayList;
import java.util.List;

public class SmUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sm_user
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sm_user
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sm_user
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user
     *
     * @mbg.generated
     */
    public SmUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sm_user
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSuUserIdIsNull() {
            addCriterion("SU_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andSuUserIdIsNotNull() {
            addCriterion("SU_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSuUserIdEqualTo(Integer value) {
            addCriterion("SU_USER_ID =", value, "suUserId");
            return (Criteria) this;
        }

        public Criteria andSuUserIdNotEqualTo(Integer value) {
            addCriterion("SU_USER_ID <>", value, "suUserId");
            return (Criteria) this;
        }

        public Criteria andSuUserIdGreaterThan(Integer value) {
            addCriterion("SU_USER_ID >", value, "suUserId");
            return (Criteria) this;
        }

        public Criteria andSuUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("SU_USER_ID >=", value, "suUserId");
            return (Criteria) this;
        }

        public Criteria andSuUserIdLessThan(Integer value) {
            addCriterion("SU_USER_ID <", value, "suUserId");
            return (Criteria) this;
        }

        public Criteria andSuUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("SU_USER_ID <=", value, "suUserId");
            return (Criteria) this;
        }

        public Criteria andSuUserIdIn(List<Integer> values) {
            addCriterion("SU_USER_ID in", values, "suUserId");
            return (Criteria) this;
        }

        public Criteria andSuUserIdNotIn(List<Integer> values) {
            addCriterion("SU_USER_ID not in", values, "suUserId");
            return (Criteria) this;
        }

        public Criteria andSuUserIdBetween(Integer value1, Integer value2) {
            addCriterion("SU_USER_ID between", value1, value2, "suUserId");
            return (Criteria) this;
        }

        public Criteria andSuUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("SU_USER_ID not between", value1, value2, "suUserId");
            return (Criteria) this;
        }

        public Criteria andSuUserNameIsNull() {
            addCriterion("SU_USER_NAME is null");
            return (Criteria) this;
        }

        public Criteria andSuUserNameIsNotNull() {
            addCriterion("SU_USER_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andSuUserNameEqualTo(String value) {
            addCriterion("SU_USER_NAME =", value, "suUserName");
            return (Criteria) this;
        }

        public Criteria andSuUserNameNotEqualTo(String value) {
            addCriterion("SU_USER_NAME <>", value, "suUserName");
            return (Criteria) this;
        }

        public Criteria andSuUserNameGreaterThan(String value) {
            addCriterion("SU_USER_NAME >", value, "suUserName");
            return (Criteria) this;
        }

        public Criteria andSuUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("SU_USER_NAME >=", value, "suUserName");
            return (Criteria) this;
        }

        public Criteria andSuUserNameLessThan(String value) {
            addCriterion("SU_USER_NAME <", value, "suUserName");
            return (Criteria) this;
        }

        public Criteria andSuUserNameLessThanOrEqualTo(String value) {
            addCriterion("SU_USER_NAME <=", value, "suUserName");
            return (Criteria) this;
        }

        public Criteria andSuUserNameLike(String value) {
            addCriterion("SU_USER_NAME like", value, "suUserName");
            return (Criteria) this;
        }

        public Criteria andSuUserNameNotLike(String value) {
            addCriterion("SU_USER_NAME not like", value, "suUserName");
            return (Criteria) this;
        }

        public Criteria andSuUserNameIn(List<String> values) {
            addCriterion("SU_USER_NAME in", values, "suUserName");
            return (Criteria) this;
        }

        public Criteria andSuUserNameNotIn(List<String> values) {
            addCriterion("SU_USER_NAME not in", values, "suUserName");
            return (Criteria) this;
        }

        public Criteria andSuUserNameBetween(String value1, String value2) {
            addCriterion("SU_USER_NAME between", value1, value2, "suUserName");
            return (Criteria) this;
        }

        public Criteria andSuUserNameNotBetween(String value1, String value2) {
            addCriterion("SU_USER_NAME not between", value1, value2, "suUserName");
            return (Criteria) this;
        }

        public Criteria andSuPasswordIsNull() {
            addCriterion("SU_PASSWORD is null");
            return (Criteria) this;
        }

        public Criteria andSuPasswordIsNotNull() {
            addCriterion("SU_PASSWORD is not null");
            return (Criteria) this;
        }

        public Criteria andSuPasswordEqualTo(String value) {
            addCriterion("SU_PASSWORD =", value, "suPassword");
            return (Criteria) this;
        }

        public Criteria andSuPasswordNotEqualTo(String value) {
            addCriterion("SU_PASSWORD <>", value, "suPassword");
            return (Criteria) this;
        }

        public Criteria andSuPasswordGreaterThan(String value) {
            addCriterion("SU_PASSWORD >", value, "suPassword");
            return (Criteria) this;
        }

        public Criteria andSuPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("SU_PASSWORD >=", value, "suPassword");
            return (Criteria) this;
        }

        public Criteria andSuPasswordLessThan(String value) {
            addCriterion("SU_PASSWORD <", value, "suPassword");
            return (Criteria) this;
        }

        public Criteria andSuPasswordLessThanOrEqualTo(String value) {
            addCriterion("SU_PASSWORD <=", value, "suPassword");
            return (Criteria) this;
        }

        public Criteria andSuPasswordLike(String value) {
            addCriterion("SU_PASSWORD like", value, "suPassword");
            return (Criteria) this;
        }

        public Criteria andSuPasswordNotLike(String value) {
            addCriterion("SU_PASSWORD not like", value, "suPassword");
            return (Criteria) this;
        }

        public Criteria andSuPasswordIn(List<String> values) {
            addCriterion("SU_PASSWORD in", values, "suPassword");
            return (Criteria) this;
        }

        public Criteria andSuPasswordNotIn(List<String> values) {
            addCriterion("SU_PASSWORD not in", values, "suPassword");
            return (Criteria) this;
        }

        public Criteria andSuPasswordBetween(String value1, String value2) {
            addCriterion("SU_PASSWORD between", value1, value2, "suPassword");
            return (Criteria) this;
        }

        public Criteria andSuPasswordNotBetween(String value1, String value2) {
            addCriterion("SU_PASSWORD not between", value1, value2, "suPassword");
            return (Criteria) this;
        }

        public Criteria andSuSexIsNull() {
            addCriterion("SU_SEX is null");
            return (Criteria) this;
        }

        public Criteria andSuSexIsNotNull() {
            addCriterion("SU_SEX is not null");
            return (Criteria) this;
        }

        public Criteria andSuSexEqualTo(String value) {
            addCriterion("SU_SEX =", value, "suSex");
            return (Criteria) this;
        }

        public Criteria andSuSexNotEqualTo(String value) {
            addCriterion("SU_SEX <>", value, "suSex");
            return (Criteria) this;
        }

        public Criteria andSuSexGreaterThan(String value) {
            addCriterion("SU_SEX >", value, "suSex");
            return (Criteria) this;
        }

        public Criteria andSuSexGreaterThanOrEqualTo(String value) {
            addCriterion("SU_SEX >=", value, "suSex");
            return (Criteria) this;
        }

        public Criteria andSuSexLessThan(String value) {
            addCriterion("SU_SEX <", value, "suSex");
            return (Criteria) this;
        }

        public Criteria andSuSexLessThanOrEqualTo(String value) {
            addCriterion("SU_SEX <=", value, "suSex");
            return (Criteria) this;
        }

        public Criteria andSuSexLike(String value) {
            addCriterion("SU_SEX like", value, "suSex");
            return (Criteria) this;
        }

        public Criteria andSuSexNotLike(String value) {
            addCriterion("SU_SEX not like", value, "suSex");
            return (Criteria) this;
        }

        public Criteria andSuSexIn(List<String> values) {
            addCriterion("SU_SEX in", values, "suSex");
            return (Criteria) this;
        }

        public Criteria andSuSexNotIn(List<String> values) {
            addCriterion("SU_SEX not in", values, "suSex");
            return (Criteria) this;
        }

        public Criteria andSuSexBetween(String value1, String value2) {
            addCriterion("SU_SEX between", value1, value2, "suSex");
            return (Criteria) this;
        }

        public Criteria andSuSexNotBetween(String value1, String value2) {
            addCriterion("SU_SEX not between", value1, value2, "suSex");
            return (Criteria) this;
        }

        public Criteria andSuEmailIsNull() {
            addCriterion("SU_EMAIL is null");
            return (Criteria) this;
        }

        public Criteria andSuEmailIsNotNull() {
            addCriterion("SU_EMAIL is not null");
            return (Criteria) this;
        }

        public Criteria andSuEmailEqualTo(String value) {
            addCriterion("SU_EMAIL =", value, "suEmail");
            return (Criteria) this;
        }

        public Criteria andSuEmailNotEqualTo(String value) {
            addCriterion("SU_EMAIL <>", value, "suEmail");
            return (Criteria) this;
        }

        public Criteria andSuEmailGreaterThan(String value) {
            addCriterion("SU_EMAIL >", value, "suEmail");
            return (Criteria) this;
        }

        public Criteria andSuEmailGreaterThanOrEqualTo(String value) {
            addCriterion("SU_EMAIL >=", value, "suEmail");
            return (Criteria) this;
        }

        public Criteria andSuEmailLessThan(String value) {
            addCriterion("SU_EMAIL <", value, "suEmail");
            return (Criteria) this;
        }

        public Criteria andSuEmailLessThanOrEqualTo(String value) {
            addCriterion("SU_EMAIL <=", value, "suEmail");
            return (Criteria) this;
        }

        public Criteria andSuEmailLike(String value) {
            addCriterion("SU_EMAIL like", value, "suEmail");
            return (Criteria) this;
        }

        public Criteria andSuEmailNotLike(String value) {
            addCriterion("SU_EMAIL not like", value, "suEmail");
            return (Criteria) this;
        }

        public Criteria andSuEmailIn(List<String> values) {
            addCriterion("SU_EMAIL in", values, "suEmail");
            return (Criteria) this;
        }

        public Criteria andSuEmailNotIn(List<String> values) {
            addCriterion("SU_EMAIL not in", values, "suEmail");
            return (Criteria) this;
        }

        public Criteria andSuEmailBetween(String value1, String value2) {
            addCriterion("SU_EMAIL between", value1, value2, "suEmail");
            return (Criteria) this;
        }

        public Criteria andSuEmailNotBetween(String value1, String value2) {
            addCriterion("SU_EMAIL not between", value1, value2, "suEmail");
            return (Criteria) this;
        }

        public Criteria andSuMobileIsNull() {
            addCriterion("SU_MOBILE is null");
            return (Criteria) this;
        }

        public Criteria andSuMobileIsNotNull() {
            addCriterion("SU_MOBILE is not null");
            return (Criteria) this;
        }

        public Criteria andSuMobileEqualTo(String value) {
            addCriterion("SU_MOBILE =", value, "suMobile");
            return (Criteria) this;
        }

        public Criteria andSuMobileNotEqualTo(String value) {
            addCriterion("SU_MOBILE <>", value, "suMobile");
            return (Criteria) this;
        }

        public Criteria andSuMobileGreaterThan(String value) {
            addCriterion("SU_MOBILE >", value, "suMobile");
            return (Criteria) this;
        }

        public Criteria andSuMobileGreaterThanOrEqualTo(String value) {
            addCriterion("SU_MOBILE >=", value, "suMobile");
            return (Criteria) this;
        }

        public Criteria andSuMobileLessThan(String value) {
            addCriterion("SU_MOBILE <", value, "suMobile");
            return (Criteria) this;
        }

        public Criteria andSuMobileLessThanOrEqualTo(String value) {
            addCriterion("SU_MOBILE <=", value, "suMobile");
            return (Criteria) this;
        }

        public Criteria andSuMobileLike(String value) {
            addCriterion("SU_MOBILE like", value, "suMobile");
            return (Criteria) this;
        }

        public Criteria andSuMobileNotLike(String value) {
            addCriterion("SU_MOBILE not like", value, "suMobile");
            return (Criteria) this;
        }

        public Criteria andSuMobileIn(List<String> values) {
            addCriterion("SU_MOBILE in", values, "suMobile");
            return (Criteria) this;
        }

        public Criteria andSuMobileNotIn(List<String> values) {
            addCriterion("SU_MOBILE not in", values, "suMobile");
            return (Criteria) this;
        }

        public Criteria andSuMobileBetween(String value1, String value2) {
            addCriterion("SU_MOBILE between", value1, value2, "suMobile");
            return (Criteria) this;
        }

        public Criteria andSuMobileNotBetween(String value1, String value2) {
            addCriterion("SU_MOBILE not between", value1, value2, "suMobile");
            return (Criteria) this;
        }

        public Criteria andSuAddressIsNull() {
            addCriterion("SU_ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andSuAddressIsNotNull() {
            addCriterion("SU_ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andSuAddressEqualTo(String value) {
            addCriterion("SU_ADDRESS =", value, "suAddress");
            return (Criteria) this;
        }

        public Criteria andSuAddressNotEqualTo(String value) {
            addCriterion("SU_ADDRESS <>", value, "suAddress");
            return (Criteria) this;
        }

        public Criteria andSuAddressGreaterThan(String value) {
            addCriterion("SU_ADDRESS >", value, "suAddress");
            return (Criteria) this;
        }

        public Criteria andSuAddressGreaterThanOrEqualTo(String value) {
            addCriterion("SU_ADDRESS >=", value, "suAddress");
            return (Criteria) this;
        }

        public Criteria andSuAddressLessThan(String value) {
            addCriterion("SU_ADDRESS <", value, "suAddress");
            return (Criteria) this;
        }

        public Criteria andSuAddressLessThanOrEqualTo(String value) {
            addCriterion("SU_ADDRESS <=", value, "suAddress");
            return (Criteria) this;
        }

        public Criteria andSuAddressLike(String value) {
            addCriterion("SU_ADDRESS like", value, "suAddress");
            return (Criteria) this;
        }

        public Criteria andSuAddressNotLike(String value) {
            addCriterion("SU_ADDRESS not like", value, "suAddress");
            return (Criteria) this;
        }

        public Criteria andSuAddressIn(List<String> values) {
            addCriterion("SU_ADDRESS in", values, "suAddress");
            return (Criteria) this;
        }

        public Criteria andSuAddressNotIn(List<String> values) {
            addCriterion("SU_ADDRESS not in", values, "suAddress");
            return (Criteria) this;
        }

        public Criteria andSuAddressBetween(String value1, String value2) {
            addCriterion("SU_ADDRESS between", value1, value2, "suAddress");
            return (Criteria) this;
        }

        public Criteria andSuAddressNotBetween(String value1, String value2) {
            addCriterion("SU_ADDRESS not between", value1, value2, "suAddress");
            return (Criteria) this;
        }

        public Criteria andSuStatusIsNull() {
            addCriterion("SU_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andSuStatusIsNotNull() {
            addCriterion("SU_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andSuStatusEqualTo(Integer value) {
            addCriterion("SU_STATUS =", value, "suStatus");
            return (Criteria) this;
        }

        public Criteria andSuStatusNotEqualTo(Integer value) {
            addCriterion("SU_STATUS <>", value, "suStatus");
            return (Criteria) this;
        }

        public Criteria andSuStatusGreaterThan(Integer value) {
            addCriterion("SU_STATUS >", value, "suStatus");
            return (Criteria) this;
        }

        public Criteria andSuStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("SU_STATUS >=", value, "suStatus");
            return (Criteria) this;
        }

        public Criteria andSuStatusLessThan(Integer value) {
            addCriterion("SU_STATUS <", value, "suStatus");
            return (Criteria) this;
        }

        public Criteria andSuStatusLessThanOrEqualTo(Integer value) {
            addCriterion("SU_STATUS <=", value, "suStatus");
            return (Criteria) this;
        }

        public Criteria andSuStatusIn(List<Integer> values) {
            addCriterion("SU_STATUS in", values, "suStatus");
            return (Criteria) this;
        }

        public Criteria andSuStatusNotIn(List<Integer> values) {
            addCriterion("SU_STATUS not in", values, "suStatus");
            return (Criteria) this;
        }

        public Criteria andSuStatusBetween(Integer value1, Integer value2) {
            addCriterion("SU_STATUS between", value1, value2, "suStatus");
            return (Criteria) this;
        }

        public Criteria andSuStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("SU_STATUS not between", value1, value2, "suStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sm_user
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sm_user
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}