package com.cn.model;

import java.io.Serializable;

public class SmUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_user.SU_USER_ID
     *
     * @mbg.generated
     */
    private Integer suUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_user.SU_USER_NAME
     *
     * @mbg.generated
     */
    private String suUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_user.SU_PASSWORD
     *
     * @mbg.generated
     */
    private String suPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_user.SU_SEX
     *
     * @mbg.generated
     */
    private String suSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_user.SU_EMAIL
     *
     * @mbg.generated
     */
    private String suEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_user.SU_MOBILE
     *
     * @mbg.generated
     */
    private String suMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_user.SU_ADDRESS
     *
     * @mbg.generated
     */
    private String suAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_user.SU_STATUS
     *
     * @mbg.generated
     */
    private Integer suStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sm_user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_user.SU_USER_ID
     *
     * @return the value of sm_user.SU_USER_ID
     *
     * @mbg.generated
     */
    public Integer getSuUserId() {
        return suUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_user.SU_USER_ID
     *
     * @param suUserId the value for sm_user.SU_USER_ID
     *
     * @mbg.generated
     */
    public void setSuUserId(Integer suUserId) {
        this.suUserId = suUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_user.SU_USER_NAME
     *
     * @return the value of sm_user.SU_USER_NAME
     *
     * @mbg.generated
     */
    public String getSuUserName() {
        return suUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_user.SU_USER_NAME
     *
     * @param suUserName the value for sm_user.SU_USER_NAME
     *
     * @mbg.generated
     */
    public void setSuUserName(String suUserName) {
        this.suUserName = suUserName == null ? null : suUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_user.SU_PASSWORD
     *
     * @return the value of sm_user.SU_PASSWORD
     *
     * @mbg.generated
     */
    public String getSuPassword() {
        return suPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_user.SU_PASSWORD
     *
     * @param suPassword the value for sm_user.SU_PASSWORD
     *
     * @mbg.generated
     */
    public void setSuPassword(String suPassword) {
        this.suPassword = suPassword == null ? null : suPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_user.SU_SEX
     *
     * @return the value of sm_user.SU_SEX
     *
     * @mbg.generated
     */
    public String getSuSex() {
        return suSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_user.SU_SEX
     *
     * @param suSex the value for sm_user.SU_SEX
     *
     * @mbg.generated
     */
    public void setSuSex(String suSex) {
        this.suSex = suSex == null ? null : suSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_user.SU_EMAIL
     *
     * @return the value of sm_user.SU_EMAIL
     *
     * @mbg.generated
     */
    public String getSuEmail() {
        return suEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_user.SU_EMAIL
     *
     * @param suEmail the value for sm_user.SU_EMAIL
     *
     * @mbg.generated
     */
    public void setSuEmail(String suEmail) {
        this.suEmail = suEmail == null ? null : suEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_user.SU_MOBILE
     *
     * @return the value of sm_user.SU_MOBILE
     *
     * @mbg.generated
     */
    public String getSuMobile() {
        return suMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_user.SU_MOBILE
     *
     * @param suMobile the value for sm_user.SU_MOBILE
     *
     * @mbg.generated
     */
    public void setSuMobile(String suMobile) {
        this.suMobile = suMobile == null ? null : suMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_user.SU_ADDRESS
     *
     * @return the value of sm_user.SU_ADDRESS
     *
     * @mbg.generated
     */
    public String getSuAddress() {
        return suAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_user.SU_ADDRESS
     *
     * @param suAddress the value for sm_user.SU_ADDRESS
     *
     * @mbg.generated
     */
    public void setSuAddress(String suAddress) {
        this.suAddress = suAddress == null ? null : suAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_user.SU_STATUS
     *
     * @return the value of sm_user.SU_STATUS
     *
     * @mbg.generated
     */
    public Integer getSuStatus() {
        return suStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_user.SU_STATUS
     *
     * @param suStatus the value for sm_user.SU_STATUS
     *
     * @mbg.generated
     */
    public void setSuStatus(Integer suStatus) {
        this.suStatus = suStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", suUserId=").append(suUserId);
        sb.append(", suUserName=").append(suUserName);
        sb.append(", suPassword=").append(suPassword);
        sb.append(", suSex=").append(suSex);
        sb.append(", suEmail=").append(suEmail);
        sb.append(", suMobile=").append(suMobile);
        sb.append(", suAddress=").append(suAddress);
        sb.append(", suStatus=").append(suStatus);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SmUser other = (SmUser) that;
        return (this.getSuUserId() == null ? other.getSuUserId() == null : this.getSuUserId().equals(other.getSuUserId()))
            && (this.getSuUserName() == null ? other.getSuUserName() == null : this.getSuUserName().equals(other.getSuUserName()))
            && (this.getSuPassword() == null ? other.getSuPassword() == null : this.getSuPassword().equals(other.getSuPassword()))
            && (this.getSuSex() == null ? other.getSuSex() == null : this.getSuSex().equals(other.getSuSex()))
            && (this.getSuEmail() == null ? other.getSuEmail() == null : this.getSuEmail().equals(other.getSuEmail()))
            && (this.getSuMobile() == null ? other.getSuMobile() == null : this.getSuMobile().equals(other.getSuMobile()))
            && (this.getSuAddress() == null ? other.getSuAddress() == null : this.getSuAddress().equals(other.getSuAddress()))
            && (this.getSuStatus() == null ? other.getSuStatus() == null : this.getSuStatus().equals(other.getSuStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSuUserId() == null) ? 0 : getSuUserId().hashCode());
        result = prime * result + ((getSuUserName() == null) ? 0 : getSuUserName().hashCode());
        result = prime * result + ((getSuPassword() == null) ? 0 : getSuPassword().hashCode());
        result = prime * result + ((getSuSex() == null) ? 0 : getSuSex().hashCode());
        result = prime * result + ((getSuEmail() == null) ? 0 : getSuEmail().hashCode());
        result = prime * result + ((getSuMobile() == null) ? 0 : getSuMobile().hashCode());
        result = prime * result + ((getSuAddress() == null) ? 0 : getSuAddress().hashCode());
        result = prime * result + ((getSuStatus() == null) ? 0 : getSuStatus().hashCode());
        return result;
    }
}