package com.cn.dao;

import com.cn.model.SmComment;
import com.cn.model.SmCommentExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SmCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_comment
     *
     * @mbg.generated
     */
    long countByExample(SmCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_comment
     *
     * @mbg.generated
     */
    int deleteByExample(SmCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer scId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_comment
     *
     * @mbg.generated
     */
    int insert(SmComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_comment
     *
     * @mbg.generated
     */
    int insertSelective(SmComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_comment
     *
     * @mbg.generated
     */
    List<SmComment> selectByExample(SmCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_comment
     *
     * @mbg.generated
     */
    SmComment selectByPrimaryKey(Integer scId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_comment
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SmComment record, @Param("example") SmCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_comment
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SmComment record, @Param("example") SmCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SmComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SmComment record);

    int selectScspIdAll(Integer spId);
}