package com.cn.dao;

import com.cn.model.SmOrder;
import com.cn.model.SmOrderExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SmOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_order
     *
     * @mbg.generated
     */
    long countByExample(SmOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_order
     *
     * @mbg.generated
     */
    int deleteByExample(SmOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer soId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_order
     *
     * @mbg.generated
     */
    int insert(SmOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_order
     *
     * @mbg.generated
     */
    int insertSelective(SmOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_order
     *
     * @mbg.generated
     */
    List<SmOrder> selectByExample(SmOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_order
     *
     * @mbg.generated
     */
    SmOrder selectByPrimaryKey(Integer soId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SmOrder record, @Param("example") SmOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SmOrder record, @Param("example") SmOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SmOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SmOrder record);

    SmOrder selectByName(@Param("spName") String spName,@Param("UserName") String UserName);
}