package com.cn.dao;

import com.cn.model.SmProduct;
import com.cn.model.SmProductExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SmProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_product
     *
     * @mbg.generated
     */
    long countByExample(SmProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_product
     *
     * @mbg.generated
     */
    int deleteByExample(SmProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer spId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_product
     *
     * @mbg.generated
     */
    int insert(SmProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_product
     *
     * @mbg.generated
     */
    int insertSelective(SmProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_product
     *
     * @mbg.generated
     */
    List<SmProduct> selectByExample(SmProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_product
     *
     * @mbg.generated
     */
    SmProduct selectByPrimaryKey(Integer spId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_product
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SmProduct record, @Param("example") SmProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_product
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SmProduct record, @Param("example") SmProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SmProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SmProduct record);
}