package com.cn.dao;

import com.cn.model.SmProductCategory;
import com.cn.model.SmProductCategoryExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SmProductCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_product_category
     *
     * @mbg.generated
     */
    long countByExample(SmProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_product_category
     *
     * @mbg.generated
     */
    int deleteByExample(SmProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_product_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer spcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_product_category
     *
     * @mbg.generated
     */
    int insert(SmProductCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_product_category
     *
     * @mbg.generated
     */
    int insertSelective(SmProductCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_product_category
     *
     * @mbg.generated
     */
    List<SmProductCategory> selectByExample(SmProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_product_category
     *
     * @mbg.generated
     */
    SmProductCategory selectByPrimaryKey(Integer spcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_product_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SmProductCategory record, @Param("example") SmProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_product_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SmProductCategory record, @Param("example") SmProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_product_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SmProductCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_product_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SmProductCategory record);


    List<SmProductCategory> selectBigCategory();

    List<SmProductCategory> selectSmallCategory();

    List<SmProductCategory> selectBigandsmall(Integer spcId);
}