package com.cn.dao;

import com.cn.model.SmUser;
import com.cn.model.SmUserExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SmUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user
     *
     * @mbg.generated
     */
    long countByExample(SmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user
     *
     * @mbg.generated
     */
    int deleteByExample(SmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer suUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user
     *
     * @mbg.generated
     */
    int insert(SmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user
     *
     * @mbg.generated
     */
    int insertSelective(SmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user
     *
     * @mbg.generated
     */
    List<SmUser> selectByExample(SmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user
     *
     * @mbg.generated
     */
    SmUser selectByPrimaryKey(Integer suUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SmUser record, @Param("example") SmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SmUser record, @Param("example") SmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SmUser record);

    SmUser selectOne(int euUserId);

    SmUser selectByStauts(@Param("username") String username, @Param("password") String password);
}